### ISSUE TITLE
Issue after feat migration

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/archmage#162]
In GitLab by @mhilbrunner on Apr 12, 2023, 11:30

## Summary

After the latest migration, I can't open the sheet for some specific PC tokens as they open as a white window (but opening the actor sheets via the sidebar or other means works), while NPC sheets and the sheets for some other PC tokens are fine.

Notably, migration also fails with some console errors.

Console errors:
```js
TypeError: Failed 13th Age system migration for world scene Test: (value || []).forEach is not a function
    at BaseActor.migrateData (commons.js:5734:25)
    at BaseActor.migrateData (commons.js:7327:20)
    at TokenDocument.migrateData (commons.js:10325:37)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12701:21)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12661:33)
    at ClientDatabaseBackend.update (commons.js:6795:33)
    at async TokenDocument.updateDocuments (commons.js:6153:23)
```
```js
vue.esm-browser.js:1613 [Vue warn]: Unhandled error during execution of render function 
  at <Power power= Object actor= Object context= Object  ... > 
  at <CharPowers actor= Object context= Object tab= Object  ... > 
  at <Tab group="primary" tab= Object > 
  at <ArchmageCharacterSheet context= Object actor= Object > 
  at <App>
warn$1 @ vue.esm-browser.js:1613
vue.esm-browser.js:1613 [Vue warn]: Unhandled error during execution of render function 
  at <Power power= Object actor= Object context= Object  ... > 
  at <CharPowers actor= Object context= Object tab= Object  ... > 
  at <Tab group="primary" tab= Object > 
  at <ArchmageCharacterSheet context= Object actor= Object > 
  at <App>
warn$1 @ vue.esm-browser.js:1613
vue.esm-browser.js:1613 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Power power= Object actor= Object context= Object  ... > 
  at <CharPowers actor= Object context= Object tab= Object  ... > 
  at <Tab group="primary" tab= Object > 
  at <ArchmageCharacterSheet context= Object actor= Object > 
  at <App>
```
```js
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'value')
[Detected 1 package: system:archmage]
    at Power.vue:26:89
    at renderList (vue.esm-browser.js:4442:26)
    at Proxy._sfc_render$k (Power.vue:34:13)
    at renderComponentRoot (vue.esm-browser.js:2464:44)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7055:57)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at render (vue.esm-browser.js:7683:13)
    at mount (vue.esm-browser.js:5924:25)
    at app.mount (vue.esm-browser.js:10839:23)
    at actor-sheet-v2.js:165:36
```
```js
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'value')
[Detected 1 package: system:archmage]
    at Power.vue:26:89
    at renderList (vue.esm-browser.js:4442:26)
    at Proxy._sfc_render$k (Power.vue:34:13)
    at renderComponentRoot (vue.esm-browser.js:2464:44)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7055:57)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at setupRenderEffect (vue.esm-browser.js:7183:9)
    at mountComponent (vue.esm-browser.js:6965:9)
    at processComponent (vue.esm-browser.js:6923:17)
    at patch (vue.esm-browser.js:6525:21)
    at mountChildren (vue.esm-browser.js:6710:13)
    at processFragment (vue.esm-browser.js:6882:13)
    at patch (vue.esm-browser.js:6518:17)
    at mountChildren (vue.esm-browser.js:6710:13)
    at mountElement (vue.esm-browser.js:6620:17)
    at processElement (vue.esm-browser.js:6602:13)
    at patch (vue.esm-browser.js:6522:21)
    at ReactiveEffect.componentUpdateFn [as fn] (vue.esm-browser.js:7062:21)
    at ReactiveEffect.run (vue.esm-browser.js:610:25)
    at instance.update (vue.esm-browser.js:7169:56)
    at callWithErrorHandling (vue.esm-browser.js:1730:36)
    at flushJobs (vue.esm-browser.js:1964:17)
    at flushJobs (vue.esm-browser.js:1979:13)
```

## Labels (do-not-change)

/cc @Asacolips @cswendrowski @LegoFed3

**Comment by asacolips** [comment]
In GitLab by @LegoFed3 on Apr 12, 2023, 13:32

mentioned in commit e3ceba5ed29672e35e212c60ea0904d011bae5a8
