### ISSUE TITLE
Effect name is not saved when edited

### ISSUE THREAD

**Issue by asacolips** [asacolips-projects/archmage#170]
In GitLab by @freohr on Oct 6, 2023, 11:16

## Summary

When I try to edit the name for an active effect, the field's value is changed but it is not saved on the character's sheet, and I get an error message on the console that the corresponding field in the JS object has been migrated.

## Steps to reproduce

(How one can reproduce the issue - this is very important)

1. Open an Actor sheet for a character
2. Create an new effect on the "Effects" tab
3. Attempt to edit the effect's name field

## What is the current bug behavior?

The name is not updated on the character's sheet, and resets to "New effect" when I close the effect edit window and re-open it.

## What is the expected correct behavior?

When I edit the effect's name, it should be updated on the character's sheet and be displayed when I close and re-open the effect's editing sheet

## Relevant logs and/or screenshots

```
Foundry VTT | Rendering EffectArchmageSheet
commons.js:2065 Error: You are accessing ActiveEffect#label which has been migrated to ActiveEffect#name
Deprecated since Version 11
Backwards-compatible support will be removed in Version 13
    at logCompatibilityWarning (commons.js:2054:19)
    at ActiveEffect._logDataFieldMigration (commons.js:8528:14)
    at ActiveEffect.get (commons.js:9000:28)
    at lookupProperty (handlebars.min.js:27:16153)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:13:133)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at renderTemplate (foundry.js:7685:10)
    at async EffectArchmageSheet._renderInner (foundry.js:5915:16)
```

## Possible fixes (optional, remove this section if unneeded)

(If you can, link to the line of code that might be responsible for the problem)

## Labels (do-not-change)

/cc @Asacolips @cswendrowski @LegoFed3

**Comment by asacolips** [comment]
In GitLab by @LegoFed3 on Oct 6, 2023, 13:46

Issue already discovered (but thanks for reporting it!) and solved in !370, closing.
